# Generated by Django 3.2.9 on 2023-06-15 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_story_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.profile'),
        ),
    ]
