# Generated by Django 4.0.8 on 2023-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_advertising',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
