# Generated by Django 3.2 on 2023-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_advertising_alter_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tillar',
            field=models.CharField(choices=[('russian', 'Russian'), ('uzbek', 'Uzbek'), ('english', 'English')], default='', max_length=25),
            preserve_default=False,
        ),
    ]
