# Generated by Django 3.2 on 2023-05-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tillar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tillar',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='blog.category'),
        ),
    ]
